### ISSUE TITLE
Some configuration maintenance in l10n-finland

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-finland#17]
Hi there!

I had to disable branch protection rules in this repo, because the OCA maintenance bots (readme generator, weblate) do push directly without PR.

**Comment by jarmokortetjarvi** [comment]
Good to know. The protection rules were set up to prevent human errors on the process, but I guess we'll have to manage without.

**Comment by sbidoul** [comment]
Yes it would be nice if we could apply these rules. Perhaps we need a separate team with admin permissions for the bots.
