### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-finland#52]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] l10n_fi_business_code
- [ ] l10n_fi_edicode
- [ ] l10n_fi_sale_refund_payment_reference

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by jarmokortetjarvi** [comment]
`l10n_fi_business_code` #53

**Comment by jarmokortetjarvi** [comment]
`l10n_fi_edicode` #55

**Comment by jarmokortetjarvi** [comment]
I think it's safe to assume these modules will not be migrated to `16.0` anymore.
They have been migrated to `17.0`, and partially to `18.0`
