### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-finland#9]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] l10n_fi_banks
- [ ] l10n_fi_payment_terms

**Comment by aisopuro** [comment]
I'll work on `l10n_fi_banks` and `l10n_fi_business_code` and `l10n_fi_business_code_validate`.

**Comment by jarmokortetjarvi** [comment]
I'm closing the migration-issues for unsupported versions.
It's very unlikely that anyone would migrate any modules in them.
